### ISSUE TITLE
Python 8 build

### ISSUE THREAD

**Issue by devaskim** [icemachined/jep-distro#1]
If it is possible, please, add prebuilt libraries for Python 8.
or
Share instructions how to build for x32 on x64 Windows/Ubuntu.

Thanks in advance

**Comment by icemachined** [comment]
Thanks you for the request. The issue was fixed in the latest release https://github.com/icemachined/jep-distro/releases/tag/4.2.0

**Comment by icemachined** [comment]
fixed in [4.2.0](https://github.com/icemachined/jep-distro/releases/tag/4.2.0)
